[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
fs_permissions = [{ access = "read", path = "./deployments"}, { access = "read", path = "./out"}, { access = "read", path = "./contexts.json"}]

# used for dev
allow_paths = ["../../"]
